### ISSUE TITLE
FCS errors

### ISSUE THREAD

**Issue by DLBPointon** [ncbi/fcs-gx#14]
Hi all,

I'm testing the versions of fcs-gx as I need to replicate the output of another pipeline (proving more difficult than it really should be). In testing various versions, I'm getting intermittent faults (across them all) which kill the tool and pipeline. Much of the time, this is a pretty simple taxid issue; we just need to go up a branch in the tree and use that ID (perhaps that could be automatic?) or we just restart the pipeline and hope it goes through, although this isn't really scalable.

But recently there have been alot of:

```
Error: Process failed with retcode -13: ['cat', 'mMusErm2-2025-sanitise-nf-ascc-filtered.fa'])                                                                                                   ]  7% ETA 0:31:32
Error: Process failed with retcode 1: ['tee', '/dev/fd/6'])


-----------------------------------------------------------------------------
Prefetching /tmp/tol_data/fcs-gx/2023-01-24/all.gxs 62%...
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_msla2zw6/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 1091, in <module>
    main()
  File "/tmp/Bazel.runfiles_msla2zw6/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 1066, in main
    run_gx_pipeline(args)
  File "/tmp/Bazel.runfiles_msla2zw6/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 709, in run_gx_pipeline
    with ProcessPipeline() as p_main:
  File "/tmp/Bazel.runfiles_msla2zw6/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 289, in __exit__
    self.wait()
  File "/tmp/Bazel.runfiles_msla2zw6/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 279, in wait
    assert num_errors == 0, "Had errors."
           ^^^^^^^^^^^^^^^
AssertionError: Had errors.
```

& especially

```
Prefetched 2023-01-24/all.gxi in 872.421s; 0.36819 GB/s. The file is 100% in RAM.
Collecting masking statistics...
Using GX_NUM_CORES=32
Fatal error: Stream  terminated abnormally.
Warning: missing header '##[["GX hits",2,1]]'
Error: Process failed with retcode 1: ['nice', '-n19', '/app/bin/gx', 'align', '--gx-db=2023-01-24/all.gxi', '--repeats-basis-fa=/dev/fd/4'])
Error: Process failed with retcode -13: ['cat', 'mMusErm2_HAPLO_filtered.fasta'])

-----------------------------------------------------------------------------

Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_2h6exxoz/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 1091, in <module>
    main()
  File "/tmp/Bazel.runfiles_2h6exxoz/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 1066, in main
    run_gx_pipeline(args)
  File "/tmp/Bazel.runfiles_2h6exxoz/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 709, in run_gx_pipeline
    with ProcessPipeline() as p_main:
  File "/tmp/Bazel.runfiles_2h6exxoz/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 289, in __exit__
    self.wait()
  File "/tmp/Bazel.runfiles_2h6exxoz/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 279, in wait
    assert num_errors == 0, "Had errors."
           ^^^^^^^^^^^^^^^
AssertionError: Had errors.
~
```

The pipeline runs 2 instances of FCS in parallel. Could this be a chunk of the issue?

This occurs seemingly at random through the process, sometimes after taxify and later stages, sometimes straight away. This is when running it in a singularity container both by it self AND in a our pipelines. It's not always the same debug stack either. Only a handful of times is it to do with the database prefetching.

The DB is synced to our /tmp nodes on hugememory nodes at the Sanger HPC by @muffato (Apologies for the suprise tag, i'm looping you in incase this becomes an infrastructure issue), and hasn't shown any signs of corruption.

Any help would be much appreciated. Thank you.

**Comment by DLBPointon** [comment]
There's also this error:
```
Prefetched 2023-01-24/all.gxi in 832.083s; 0.386039 GB/s. The file is 100% in RAM.
Collecting masking statistics...
Using GX_NUM_CORES=32
Collected masking stats:  7.2806e-05 Gbp; 1.63515s; 0.0445254 Mbp/s. Baseline: 1.00278

Using GX_NUM_CORES=32
Processed 1 queries, 0.244661Mbp in 0.808089s. (0.302763Mbp/s); num-jobs:3

-----------------------------------------------------------------------------

Traceback (most recent call last):
  File "/usr/local/bin/run_gx.py", line 1202, in <module>
    main()
    ~~~~^^
  File "/usr/local/bin/run_gx.py", line 1177, in main
    run_gx_pipeline(args)
    ~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/bin/run_gx.py", line 811, in run_gx_pipeline
    with ProcessPipeline() as p_zcat_fasta:
         ~~~~~~~~~~~~~~~^^
  File "/usr/local/bin/run_gx.py", line 344, in __exit__
    self.wait()
    ~~~~~~~~~^^
  File "/usr/local/bin/run_gx.py", line 334, in wait
    assert num_errors == 0, "Had errors."
           ^^^^^^^^^^^^^^^
AssertionError: Had errors.
```

Something to do with the fasta file, in this case it is taking a single scaffold mito.

**Comment by muffato** [comment]
> The pipeline runs 2 instances of FCS in parallel. Could this be a chunk of the issue?

In parallel on the same machine or different machines ? Also, they run in different directories, right ?

**Comment by DLBPointon** [comment]
In parallel as in Nextflow will run them at the same time, always in different directories.

Sometimes this will be the same machine, luck of the draw on the farm, I guess. This looks to be killing everything James runs on the farm.

**Comment by DLBPointon** [comment]
If this is a case of the nextflow process containing FCS-GX not being able to be run in multiple instances at the same time then we can patch the module to use `maxForks 1` (Run one instance at a time) and just deal with the fact that it may slow things down a bit.

Will potentially not help when running the pipeline at scale though.

**Comment by etvedte** [comment]
> In testing various versions, I'm getting intermittent faults (across them all) which kill the tool and pipeline

For the three errors above, are you seeing them all on the latest version (0.5.5), or are some restricted only to older versions? For example, in 0.5.5 we implemented a fix for errors that were occurring when two GX processes were simultaneously accessing the input FASTA.

>  Much of the time, this is a pretty simple taxid issue; we just need to go up a branch in the tree and use that ID

Can you give me an example of where this occurs?

**Comment by DLBPointon** [comment]
Yes it's happened on the latest where i've been using 0.5.5-9 ( provided by galaxy - https://depot.galaxyproject.org/singularity/ncbi-fcs-gx%3A0.5.5--h9948957_0 ).

This happened with Mustela erminea - 36723, and we had to go up a branch to mustela - 9665. This does still crash occasionally, however, I'm starting to wonder whether this is not a taxify issue and is related to whatever odd thing is going on above, causing crashes in odd places?

**Comment by etvedte** [comment]
Please try with your 0.5.5, setting this in your [env file:](https://github.com/ncbi/fcs/wiki/FCS-GX-input#environment-variables)
`GX_INSTANTIATE_FASTA=1` 

The two simultaneous access problem I mentioned above requires this env variable to be set. We'll need to document this better.

**Comment by DLBPointon** [comment]
Hi @etvedte

Ran this last night and it crashed with the below, i'm not sure how related that is so I will run it again to make sure.

These errors are definitely only happening in cases where there are 2 or more instances running though, could it be the multiple accesses to the DB? and It is just co-incedental that these jobs are always hitting the same node with the same DB?

```
Note: detected page-faults (disk-thrashing) - GX may run slowly.
Consider placing gxdb into non-swappable ramfs/tmpfs, or use `vmtouch -l`.

NB: taxify.cpp:840 in operator()(...) while processing HAP2_SCAFFOLD_12~62952503..84830353...
Fatal error: taxify.cpp:847 in process_qry(...): Assertion failed: qry_len != k_invalid_len
Error: Process failed with retcode 32: ['pv', '--quiet', '--buffer-size=104857600'])
Error: Process failed with retcode 1: ['/usr/local/bin/gx', 'taxify', '--gx-db=2023-01-24/all.gxi', '--output=./mMusErm2_HAPLO.taxonomy.rpt.tmp', '--asserted-div=anml:mammals'])

-----------------------------------------------------------------------------

Traceback (most recent call last):
  File "/usr/local/bin/run_gx.py", line 1202, in <module>
    main()
    ~~~~^^
  File "/usr/local/bin/run_gx.py", line 1177, in main
    run_gx_pipeline(args)
    ~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/bin/run_gx.py", line 817, in run_gx_pipeline
    run(p_zcat_fasta, p_get_fasta_stats, p_save_hits, p_main, tmp_instantiated_fasta_path)
    ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/run_gx.py", line 808, in run
    p_main.wait()
    ~~~~~~~~~~~^^
  File "/usr/local/bin/run_gx.py", line 334, in wait
    assert num_errors == 0, "Had errors."
           ^^^^^^^^^^^^^^^
AssertionError: Had errors.
```

**Comment by etvedte** [comment]
Hi @DLBPointon ,

Users previously reported similar symptoms in https://github.com/ncbi/fcs/issues/80  (indicated by internal gx processes exiting with error-code -13 (EACCES)).

The investigation concluded that the most likely cause is the [known problem](https://pawsey.atlassian.net/wiki/spaces/US/pages/51929082/Known+Issues+on+Setonix#KnownIssuesonSetonix-ParallelIOwithinContainers) with containerization software running in certain HPC environments, where multiple processes access the same file simultaneously.

We were not able to reproduce it locally, absent the same environment, but the putative fix was implemented here:
https://github.com/ncbi/fcs-gx/blob/07ffe78e863444fc4dace1762c29a20fef9d263b/scripts/run_gx.py#L721

So from what I've gathered your errors are intermittent, and none appear to be deterministic, correct?

If it's intermittent and only happens when there are multiple simultaneous accesses to the db, then it could be the same issue with the HPC environment referenced above. GX access to db-files is read-only and we've never had any problems with it.

One option that might work is the `maxForks 1` you suggested above. GX isn't too time-consuming, so it shouldn't throttle your workflows by a lot. An alternative solution is to build and run GX natively outside of a container.

**Comment by DLBPointon** [comment]
Ok, we'll need to do more testing then. This isn't something that we've come across before using the previous version (of the pipeline and fcs-gx), but then again that was loading the db into mem and then running each assembly sequentially in the same container.

I've dropped in the `maxForks 1` and we'll see how that goes for now. I'm running 4 samples (containing both hap1,2 and organellar assemblies) so we'll see what breaks first. I'll let you know.

**Comment by DLBPointon** [comment]
Hi all, so I've had a dozen samples go through now (hap1,hap2 and organellar each getting their own FCS instance) without issue.

It could be a coincidence that no jobs have collided, but for now, it looks promising.

I tried a few runs with `GX_INSTANTIATE_FASTA=1` and each crashed with bizarre errors which hadn't come up before. Annoyingly, the errors that I saved have all disappeared. Instead, I've used `cp 'realpath {fasta}' input.fasta` to copy the file into the container and that seems to work well. So maybe a container issue with tmp files?

I've also employed `maxForks 1` mentioned before which may be doing a majority of the work in this case. For now, however, the issue seems solved on my end by running with:

```
    export GX_NUM_CORES=${task.cpus}

    cp `readlink ${fasta}` ${prefix}_copied_input.fasta

    run_gx.py \\
        --fasta ${prefix}_copied_input.fasta \\
        --gx-db ${database} \\
        --tax-id ${meta.taxid} \\
        --generate-logfile true \\
        --out-basename ${prefix} \\
        --out-dir . \\
        ${args}
```

**Comment by DLBPointon** [comment]
Saying that, a new assembly has just failed with this error, which may or maynot be related:
```
Prefetched 2023-01-24/all.gxi in 716.801s; 0.448126 GB/s. The file is 100% in RAM.
Collecting masking statistics...
Using GX_NUM_CORES=32
Collected masking stats:  7.2801e-05 Gbp; 1.85996s; 0.0391411 Mbp/s. Baseline: 3.2501

Using GX_NUM_CORES=32


Note: detected page-faults (disk-thrashing) - GX may run slowly.
Consider placing gxdb into non-swappable ramfs/tmpfs, or use `vmtouch -l`.

Error: Process failed with retcode -15: ['/usr/local/bin/gx', 'split-fasta'])


     ********************************************************
     *
     *  Note: the command was terminated by a signal SIGTERM
     *
     ********************************************************
NB: taxify.cpp:840 in operator()(...) while processing HAP2_SCAFFOLD_5~7086897..11524401...
Fatal error: taxify.cpp:847 in process_qry(...): Assertion failed: qry_len != k_invalid_len
Error: Process failed with retcode 32: ['pv', '--quiet', '--buffer-size=104857600'])
Error: Process failed with retcode 1: ['/usr/local/bin/gx', 'taxify', '--gx-db=2023-01-24/all.gxi', '--output=./ihMegChia1_HAPLO.taxonomy.rpt.tmp', '--asserted-div=anml:insects'])

-----------------------------------------------------------------------------

Traceback (most recent call last):
  File "/usr/local/bin/run_gx.py", line 1202, in <module>
    main()
    ~~~~^^
  File "/usr/local/bin/run_gx.py", line 1177, in main
    run_gx_pipeline(args)
    ~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/bin/run_gx.py", line 817, in run_gx_pipeline
    run(p_zcat_fasta, p_get_fasta_stats, p_save_hits, p_main, tmp_instantiated_fasta_path)
    ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/run_gx.py", line 808, in run
    p_main.wait()
    ~~~~~~~~~~~^^
  File "/usr/local/bin/run_gx.py", line 334, in wait
    assert num_errors == 0, "Had errors."
           ^^^^^^^^^^^^^^^
AssertionError: Had errors.
~
```

I've added a line to hard copy the assembly into the container now, see if that helps at all in this case.

**Comment by DLBPointon** [comment]
I've just written a few scripts to go through the logs.

To me it deffinately looks like and issue with multiple instances trying to access the logs:

```
qmSphVire4_HAPLO_GENOMIC
	- NODE: tol-1-9-2
	- STAT: SUCCESS
	- TIME: Mon Jul 14 15:11:25 2025

	- LOGS: /lustre/scratch124/tol/teams/tola/users/dp24/ascc/qmSphVire4/work/24/783200c164e415e2d9ccdcd59ddb28/.command.log

qmSphVire4_MITO_ORGANELLAR
	- NODE: tol-1-10-1
	- STAT: SUCCESS
	- TIME: Mon Jul 14 14:37:55 2025

	- LOGS: /lustre/scratch124/tol/teams/tola/users/dp24/ascc/qmSphVire4/work/99/7f6ba7241726e4e8c7365e033fad13/.command.log

qmSphVire4_PRIMARY_GENOMIC
	- NODE: tol-1-10-1
	- STAT: FAILED
	- TIME: Mon Jul 14 14:54:59 2025

	- LOGS: /lustre/scratch124/tol/teams/tola/users/dp24/ascc/qmSphVire4/work/21/ea1b60f8061f444ba87948c53feb95/.command.log
```

Same node, at the same time will always cause the second starting job to fail. Same pattern through out the log file.

`maxForks 1` shouldn't be allowing the jobs to start at the same time anyway so i'm a little confused there.

**Comment by DLBPointon** [comment]
Not perfect though
```
idDicFenn1_HAPLO_GENOMIC
	- NODE: tol-1-9-2
	- STAT: SUCCESS
	- TIME: Mon Jul 14 15:03:49 2025

	- LOGS: /lustre/scratch124/tol/teams/tola/users/dp24/ascc/idDicFenn1/work/3b/7f5b9afeadd8052ccfba9af78be6a6/.command.log

idDicFenn1_MITO_ORGANELLAR
	- NODE: tol-1-9-2
	- STAT: SUCCESS
	- TIME: Mon Jul 14 15:03:35 2025

	- LOGS: /lustre/scratch124/tol/teams/tola/users/dp24/ascc/idDicFenn1/work/61/aeef9af2298a4b0d6ddc031a92b244/.command.log

idDicFenn1_PRIMARY_GENOMIC
	- NODE: tol-1-9-2
	- STAT: SUCCESS
	- TIME: Mon Jul 14 15:07:20 2025

	- LOGS: /lustre/scratch124/tol/teams/tola/users/dp24/ascc/idDicFenn1/work/b8/5557cd938c4fa2de63a07f570600f0/.command.log
```

**Comment by muffato** [comment]
> ```
> qmSphVire4_MITO_ORGANELLAR
> 	- NODE: tol-1-10-1
> 	- STAT: SUCCESS
> 	- TIME: Mon Jul 14 14:37:55 2025
> 
> 	- LOGS: /lustre/scratch124/tol/teams/tola/users/dp24/ascc/qmSphVire4/work/99/7f6ba7241726e4e8c7365e033fad13/.command.log
> 
> qmSphVire4_PRIMARY_GENOMIC
> 	- NODE: tol-1-10-1
> 	- STAT: FAILED
> 	- TIME: Mon Jul 14 14:54:59 2025
> 
> 	- LOGS: /lustre/scratch124/tol/teams/tola/users/dp24/ascc/qmSphVire4/work/21/ea1b60f8061f444ba87948c53feb95/.command.log
> ```
> 
> Same node, at the same time will always cause the second starting job to fail. Same pattern through out the log file.

They actually didn't run _at the same time_. The first one started at 14:37:58 and finished (successfully) at 14:54:59. The second one started at 14:54:59 and failed at 15:11:31.
Given both jobs had requested 400 GB RAM and the machine only has ~750 GB RAM, LSF couldn't possibly run both simultaneously.

**Comment by LaurenHuet** [comment]
Hi, I debated on creating a new issue, but my errors look so similar, and I'm running this at scale as well, so i thought i might just add them in here, if need to delete and create a new issue let me know, happy to do that. 
I have started getting a lot of errors with this process recently which look very similar to the ones SANGER is getting. I run it on HPC, each job just loads the database into RAM first then runs, as were not allowed to load the database into tmfps on my cluster. I'm using singularity and nextflow to run jobs, i'm using this container 'docker.io/ncbi/fcs-gx:0.5.5' with this code 

 ```
   python3 /app/bin/run_gx \\
        --fasta $assembly \\
        --out-dir ./out \\
        --gx-db $gxdb \\
        --tax-id ${meta.taxid} \\
        --out-basename ${prefix}_${haplotype}.${meta.taxid} \\
        $args
```

these are the errors i have been getting 

```
Note: detected page-faults (disk-thrashing) - GX may run slowly.
Consider placing gxdb into non-swappable ramfs/tmpfs, or use `vmtouch -l`.

Error: Process failed with retcode 32: ['pv', '-Wbratpe', '--interval=0.5', '--size=639987775', '--buffer-size=104857600'])
NB: taxify.cpp:817 in operator()(...) while processing scaffold_1~3829627..16746265...
Fatal error: taxify.cpp:824 in process_qry(...): Assertion failed: qry_len != k_invalid_len
Error: Process failed with retcode 32: ['pv', '--quiet', '--buffer-size=104857600'])
Error: Process failed with retcode 1: ['/app/bin/gx', 'taxify', '--gx-db=gxdb/all.gxi', '--output=./out/OG686_v241004.hic1_.1.yahs.hap1.NCBI.3040455.taxonomy.rpt.tmp', '--asserted-div=anml:fishes', '--db-exclude-locs=/app/bin/db_exclude.locs.tsv'])

-----------------------------------------------------------------------------

Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_ud98pa96/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 1179, in <module>
    main()
  File "/tmp/Bazel.runfiles_ud98pa96/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 1154, in main
    run_gx_pipeline(args)
  File "/tmp/Bazel.runfiles_ud98pa96/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 794, in run_gx_pipeline
    run(p_zcat_fasta, p_get_fasta_stats, p_save_hits, p_main, tmp_instantiated_fasta_path)
  File "/tmp/Bazel.runfiles_ud98pa96/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 785, in run
    p_main.wait()
  File "/tmp/Bazel.runfiles_ud98pa96/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 311, in wait
    assert num_errors == 0, "Had errors."
           ^^^^^^^^^^^^^^^
AssertionError: Had errors.
```


```
Note: detected page-faults (disk-thrashing) - GX may run slowly.
Consider placing gxdb into non-swappable ramfs/tmpfs, or use `vmtouch -l.

Exception on row: 2053205
---- fields:
scaffold_1~44733853..56317883
6553012
215358
NC_0
----
Fatal error: taxify.cpp:1235 in Taxify(...): Assertion failed: row.size() == 8
Error: Process failed with retcode 32: ['pv', '--quiet', '--buffer-size=104857600'])
Error: Process failed with retcode 1: ['/app/bin/gx', 'taxify', '--gx-db=gxdb/all.gxi', '--output=./out/OG90_v240821.hic1_.1.yahs.hap1.NCBI.2578334.taxonomy.rpt.tmp', '--asserted-div=anml:fishes', '--db-exclude-locs=/app/bin/db_exclude.locs.tsv'])

-----------------------------------------------------------------------------

Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_82iv9zop/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 1179, in <module>
    main()
  File "/tmp/Bazel.runfiles_82iv9zop/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 1154, in main
    run_gx_pipeline(args)
  File "/tmp/Bazel.runfiles_82iv9zop/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 794, in run_gx_pipeline
    run(p_zcat_fasta, p_get_fasta_stats, p_save_hits, p_main, tmp_instantiated_fasta_path)
  File "/tmp/Bazel.runfiles_82iv9zop/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 785, in run
    p_main.wait()
  File "/tmp/Bazel.runfiles_82iv9zop/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 311, in wait
    assert num_errors == 0, "Had errors."
           ^^^^^^^^^^^^^^^
AssertionError: Had errors.`
```


```
`Note: detected page-faults (disk-thrashing) - GX may run slowly.
Consider placing gxdb into non-swappable ramfs/tmpfs, or use `vmtouch -l`.

NB: taxify.cpp:817 in operator()(...) while processing scaffold_1~41793909..51630008...
Fatal error: taxify.cpp:824 in process_qry(...): Assertion failed: qry_len != k_invalid_len
Error: Process failed with retcode 32: ['pv', '--quiet', '--buffer-size=104857600'])
Error: Process failed with retcode 1: ['/app/bin/gx', 'taxify', '--gx-db=gxdb/all.gxi', '--output=./out/OG767_v250331.hic1_.1.salsa.hap1.NCBI.1856566.taxonomy.rpt.tmp', '--asserted-div=anml:fishes', '--db-exclude-locs=/app/bin/db_exclude.locs.tsv'])

-----------------------------------------------------------------------------

Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_zc1e1cxd/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 1179, in <module>
    main()
  File "/tmp/Bazel.runfiles_zc1e1cxd/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 1154, in main
    run_gx_pipeline(args)
  File "/tmp/Bazel.runfiles_zc1e1cxd/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 794, in run_gx_pipeline
    run(p_zcat_fasta, p_get_fasta_stats, p_save_hits, p_main, tmp_instantiated_fasta_path)
  File "/tmp/Bazel.runfiles_zc1e1cxd/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 785, in run
    p_main.wait()
  File "/tmp/Bazel.runfiles_zc1e1cxd/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 311, in wait
    assert num_errors == 0, "Had errors."
           ^^^^^^^^^^^^^^^
AssertionError: Had errors.`
```






```
Collecting masking statistics...
Error: Process failed with retcode -15: ['/app/bin/gx', 'split-fasta'])

 
     ******************************************************** 
     * 
     *  Note: the command was terminated by a signal SIGTERM
     * 
     ********************************************************
Warning: missing header ##[["GX hits",2,1]]
Fatal error: taxify.cpp:341 in make_run_info_json(...): Assertion failed: agg_cvg <= 1
Error: Process failed with retcode -15: ['nice', '-n19', '/app/bin/gx', 'align', '--gx-db=/tmp/gxdb/all.gxi', '--repeats-basis-fa=/dev/fd/4'])

 
     ******************************************************** 
     * 
     *  Note: the command was terminated by a signal SIGTERM
     * 
     ********************************************************
Error: Process failed with retcode 1: ['/app/bin/gx', 'taxify', '--gx-db=/tmp/gxdb/all.gxi', '--output=./out/OG767_v250331.hic1_.1.yahs.hap2.NCBI.1856566.taxonomy.rpt.tmp', '--asserted-div=anml:fishes', '--db-exclude-locs=/app/bin/db_exclude.locs.tsv'])

-----------------------------------------------------------------------------

Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_0c7u04yb/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 1179, in <module>
    main()
  File "/tmp/Bazel.runfiles_0c7u04yb/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 1154, in main
    run_gx_pipeline(args)
  File "/tmp/Bazel.runfiles_0c7u04yb/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 794, in run_gx_pipeline
    run(p_zcat_fasta, p_get_fasta_stats, p_save_hits, p_main, tmp_instantiated_fasta_path)
  File "/tmp/Bazel.runfiles_0c7u04yb/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 785, in run
    p_main.wait()
  File "/tmp/Bazel.runfiles_0c7u04yb/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 311, in wait
    assert num_errors == 0, "Had errors."
           ^^^^^^^^^^^^^^^
AssertionError: Had errors.
```




I have 7 genomes in this pipeline i am trying to run, both with HAP1 and HAP2, so far all the ones that have run have failed, but the rest of them are still in the queue, so if i get more errors i can post them. 

Cheers, 
Lauren

**Comment by etvedte** [comment]
@LaurenHuet - have you attempted any of the potential fixes reported [here](https://github.com/ncbi/fcs-gx/issues/14#issuecomment-3069657957)? We will look at the errors but want to get a sense of what you've tried.

**Comment by DLBPointon** [comment]
I'm completely stumped at this point. This is from latest testing, using the lustre based and /tmp based DB's I'm getting the below. I've pulled a bunch of stats for nodes, start and end times and there doesn't seem to be much of a pattern, works out to a 50% chance of whether it will pass or fail (skews towards bigger genomes causing a fail, for instance a bird genome failed 8 times before passing). I'll try an isolated run next (e.g. through a module vs container) and see what happens.


``` samplesheet.csv
scientific_name: "Parus major"
taxid: 9157
```

```error
     ********************************************************
     *
     *  Note: the command was terminated by a signal SIGTERM
     *
     ********************************************************
Error: Process failed with retcode 32: ['pv', '-Wbratpe', '--interval=0.5', '--size=895808500', '--buffer-size=104857600'])
NB: taxify.cpp:840 in operator()(...) while processing SCAFFOLD_2~4865446..32164705...
Fatal error: taxify.cpp:847 in process_qry(...): Assertion failed: qry_len != k_invalid_len
Error: Process failed with retcode -15: ['nice', '-n19', '/usr/local/bin/gx', 'align', '--gx-db=latest/all.gxi', '--repeats-basis-fa=/dev/fd/6'])


     ********************************************************
     *
     *  Note: the command was terminated by a signal SIGTERM
     *
     ********************************************************
Error: Process failed with retcode 1: ['/usr/local/bin/gx', 'taxify', '--gx-db=latest/all.gxi', '--output=./bParMaj1_PRIMARY.taxonomy.rpt.tmp', '--asserted-div=anml:birds'])

```

**Comment by muffato** [comment]
@DLBPointon  I noticed you "only" requested 400 GB RAM for your jobs. The [docs](https://github.com/ncbi/fcs/wiki/FCS-GX-quickstart#prerequisites) say 512 GB RAM. Could that be a reason ?

**Comment by LaurenHuet** [comment]
I've been running some tests with this command, my testing is very slow as our highmem node seems to be really backed up.

Just testing pull out the files from the gxdb that the tool actually seems to use and sticking them in tmp, then copying the fasta. 


i give following resources 

```
    withName:FCS_FCSGX_HAP1 {
        queue  = 'highmem'
        cpus   = { 32 }
        memory = { 512.GB }
        time   = { 4.h }
```


```
    
    echo 'copying database files to /tmp/'
    mkdir -p /tmp/gxdb/
    cp -v ${gxdb}/all.gxi /tmp/gxdb/
    cp -v ${gxdb}/all.gxs /tmp/gxdb/
    cp -v ${gxdb}/all.meta.jsonl /tmp/gxdb/
    cp -v ${gxdb}/all.blast_div.tsv.gz /tmp/gxdb/
    cp -v ${gxdb}/all.taxa.tsv /tmp/gxdb/
    echo 'done copying database files'
    ls -l /tmp/gxdb/


    cp `readlink ${assembly}` ${prefix}_copied_input.fasta

    python3 /app/bin/run_gx \\
        --fasta ${prefix}_copied_input.fasta \\
        --out-dir ./out \\
        --gx-db /tmp/gxdb \\
        --tax-id ${meta.taxid} \\
        --out-basename ${prefix}_${haplotype}.${meta.taxid} \\
        $args

    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        python: \$(python3 --version 2>&1 | sed -e "s/Python //g")
        FCS-GX: $FCSGX_VERSION
    END_VERSIONS
    
```


I've now had 7 of my jobs complete successfully with this, one error , and 25 in the queue waiting to be run



the error i received 

```
tax-id    : 1856566
fasta     : OG767_v240821241004.hic1.1.yahs.hap2_scaffolds_final.fa
size      : 1544.57 MiB
split-fa  : True
BLAST-div : bony fishes
gx-div    : anml:fishes
w/same-tax: True
bin-dir   : /app/bin
gx-db     : /tmp/gxdb/all.gxi build-date: 2023-01-24
gx-ver    : Mar 18 2025 11:01:26; git:v0.5.5-0-g0bda491; sqlite:3.46.1
output    : ./out/OG767_v240821241004.hic1_.1.yahs.hap2.NCBI.1856566.taxonomy.rpt

-----------------------------------------------------------------------------

Collecting masking statistics...
Error: Process failed with retcode -15: ['/app/bin/gx', 'split-fasta'])

 
     ******************************************************** 
     * 
     *  Note: the command was terminated by a signal SIGTERM
     * 
     ********************************************************
Warning: missing header '##[["GX hits",2,1]]'
Fatal error: taxify.cpp:341 in make_run_info_json(...): Assertion failed: agg_cvg <= 1
Error: Process failed with retcode -15: ['nice', '-n19', '/app/bin/gx', 'align', '--gx-db=/tmp/gxdb/all.gxi', '--repeats-basis-fa=/dev/fd/4'])

 
     ******************************************************** 
     * 
     *  Note: the command was terminated by a signal SIGTERM
     * 
     ********************************************************
Error: Process failed with retcode 1: ['/app/bin/gx', 'taxify', '--gx-db=/tmp/gxdb/all.gxi', '--output=./out/OG767_v240821241004.hic1_.1.yahs.hap2.NCBI.1856566.taxonomy.rpt.tmp', '--asserted-div=anml:fishes', '--db-exclude-locs=/app/bin/db_exclude.locs.tsv'])

-----------------------------------------------------------------------------

Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_q4yrbkdi/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 1179, in <module>
    main()
  File "/tmp/Bazel.runfiles_q4yrbkdi/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 1154, in main
    run_gx_pipeline(args)
  File "/tmp/Bazel.runfiles_q4yrbkdi/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 794, in run_gx_pipeline
    run(p_zcat_fasta, p_get_fasta_stats, p_save_hits, p_main, tmp_instantiated_fasta_path)
  File "/tmp/Bazel.runfiles_q4yrbkdi/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 785, in run
    p_main.wait()
  File "/tmp/Bazel.runfiles_q4yrbkdi/runfiles/gdh_datasets/apps/fcs_genome/public/run_gx.py", line 311, in wait
    assert num_errors == 0, "Had errors."
           ^^^^^^^^^^^^^^^
AssertionError: Had errors.

```

**Comment by DLBPointon** [comment]
@muffato 

We've historically used 400 based on testing by Eerik and Michael. I have bumped it to 520 though just in case and it's failed on all three samples i have stuck in fcs at the minute:

Almost identical to @LaurenHuet's errors above.

Parus Major
```
Using GX_NUM_CORES=32


Note: detected page-faults (disk-thrashing) - GX may run slowly.
Consider placing gxdb into non-swappable ramfs/tmpfs, or use `vmtouch -l`.

Error: Process failed with retcode -15: ['/usr/local/bin/gx', 'split-fasta'])


     ********************************************************
     *
     *  Note: the command was terminated by a signal SIGTERM
     *
     ********************************************************
Error: Process failed with retcode 32: ['pv', '-Wbratpe', '--interval=0.5', '--size=895808500', '--buffer-size=104857600'])
NB: taxify.cpp:840 in operator()(...) while processing SCAFFOLD_2~4865446..32164705...
Fatal error: taxify.cpp:847 in process_qry(...): Assertion failed: qry_len != k_invalid_len
Error: Process failed with retcode -15: ['nice', '-n19', '/usr/local/bin/gx', 'align', '--gx-db=latest/all.gxi', '--repeats-basis-fa=/dev/fd/6'])


     ********************************************************
     *
     *  Note: the command was terminated by a signal SIGTERM
     *
     ********************************************************
Error: Process failed with retcode 1: ['/usr/local/bin/gx', 'taxify', '--gx-db=latest/all.gxi', '--output=./bParMaj1_PRIMARY.taxonomy.rpt.tmp', '--asserted-div=anml:birds'])

-----------------------------------------------------------------------------

Traceback (most recent call last):
  File "/usr/local/bin/run_gx.py", line 1202, in <module>
    main()
    ~~~~^^
  File "/usr/local/bin/run_gx.py", line 1177, in main
    run_gx_pipeline(args)
    ~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/bin/run_gx.py", line 817, in run_gx_pipeline
    run(p_zcat_fasta, p_get_fasta_stats, p_save_hits, p_main, tmp_instantiated_fasta_path)
    ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/run_gx.py", line 808, in run
    p_main.wait()
    ~~~~~~~~~~~^^
  File "/usr/local/bin/run_gx.py", line 334, in wait
    assert num_errors == 0, "Had errors."
           ^^^^^^^^^^^^^^^
AssertionError: Had errors.
```

A swan of some sort:
```
Collected masking stats:  7.2801e-05 Gbp; 1.63159s; 0.0446196 Mbp/s. Baseline: 1.05525

Using GX_NUM_CORES=32
Error: Process failed with retcode -15: ['/usr/local/bin/gx', 'split-fasta'])


     ********************************************************
     *
     *  Note: the command was terminated by a signal SIGTERM
     *
     ********************************************************
Fatal error: taxify.cpp:364 in make_run_info_json(...): Assertion failed: agg_cvg <= 1
Error: Process failed with retcode -15: ['nice', '-n19', '/usr/local/bin/gx', 'align', '--gx-db=latest/all.gxi', '--repeats-basis-fa=/dev/fd/6'])

     ********************************************************
     *
     *  Note: the command was terminated by a signal SIGTERM
     *
     ********************************************************
Error: Process failed with retcode 1: ['/usr/local/bin/gx', 'taxify', '--gx-db=latest/all.gxi', '--output=./bCygCol1_PRIMARY.taxonomy.rpt.tmp', '--asserted-div=anml:birds'])

-----------------------------------------------------------------------------

Traceback (most recent call last):
  File "/usr/local/bin/run_gx.py", line 1202, in <module>
    main()
    ~~~~^^
  File "/usr/local/bin/run_gx.py", line 1177, in main
    run_gx_pipeline(args)
    ~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/bin/run_gx.py", line 817, in run_gx_pipeline
    run(p_zcat_fasta, p_get_fasta_stats, p_save_hits, p_main, tmp_instantiated_fasta_path)
    ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/run_gx.py", line 808, in run
    p_main.wait()
    ~~~~~~~~~~~^^
  File "/usr/local/bin/run_gx.py", line 334, in wait
    assert num_errors == 0, "Had errors."
           ^^^^^^^^^^^^^^^
AssertionError: Had errors.
                                                                                                         
```

Birds seem to be particularly troublesome. I don't know if that is part of the issue.

**Comment by muffato** [comment]
If it helps with helping / testing / debugging:

1. the container we use is the one from Galaxy: <https://depot.galaxyproject.org/singularity/ncbi-fcs-gx:0.5.5--h9948957_0>
2. Nextflow runs container with both `--no-home` and `--pid`
```
      --no-home                       do NOT mount users home directory if
                                      /home is not the current working
                                      directory

  -p, --pid                           run container in a new PID namespace
```

**Comment by DLBPointon** [comment]
I'm currently running FCS outside of the pipeline to see what happens, a colleuge uses it this way and has never had a crash. So a TEMPORARY sollution for us might be to run FCS externally (as @etvedte suggested somewhere in this labarynth of an issue now) and then ingest the results, however, this will require externalising a number of pre-processing steps (filtering out large scaffolds as these do effect the FCS runs).

Could there be an issue with the fasta stats generator?

This is generated for Parus Major using the same input file. But then again, I don't know if you have your own internal meanings for these or what hasher your using.

FCS-GX <-- IN SINGULARITY
`{"sum_len":36012401, "num_seqs":3, "num_Ns":500, "len_N50":35873162, "hash":"bab3e7fd1daef57a"`

FCS-GX <-- NO CONTAINER
`{"sum_len":884723958, "num_seqs":1722, "num_Ns":99800, "len_N50":21627514, "hash":"3718265b5e18f6a0"}`

GFASTATS
```
singularity exec gfastats\:1.3.10--h077b44d_0 gfastats bParMaj1_PRIMARY_copied_input.fasta
+++Assembly summary+++:
# scaffolds: 1722
Total scaffold length: 884723958
Average scaffold length: 513776.98
Scaffold N50: 21627514
Scaffold auN: 32977823.44
Scaffold L50: 10
Largest scaffold: 77679230
Smallest scaffold: 1000
# contigs: 2720
Total contig length: 884624158
Average contig length: 325229.47
Contig N50: 3043966
Contig auN: 5516127.61
Contig L50: 64
Largest contig: 27299260
Smallest contig: 1
# gaps in scaffolds: 998
Total gap length in scaffolds: 99800
Average gap length in scaffolds: 100.00
Gap N50 in scaffolds: 100
Gap auN in scaffolds: 100.00
Gap L50 in scaffolds: 499
Largest gap in scaffolds: 100
Smallest gap in scaffolds: 100
Base composition (A:C:G:T): 244008064:197769089:198115757:244731248
GC content %: 44.75
# soft-masked bases: 0
# segments: 2720
Total segment length: 884624158
Average segment length: 325229.47
# gaps: 998
# paths: 1722
```

**Comment by DLBPointon** [comment]
As a note, the local test finished. No pipeline, no container just the repo+make. It finished fine, the results are a perfectly clean genome:
```
fcs_gx_report.txt contamination summary:
----------------------------------------
                                seqs      bases
                               ----- ----------
TOTAL                              0          0
-----                          ----- ----------

-----------------------------------------------------------------------------

fcs_gx_report.txt action summary:
---------------------------------
                                seqs      bases
                               ----- ----------
TOTAL                              0          0
-----                          ----- ----------
```

Looking at the `bParMaj1_PRIMARY.taxonomy.rpt` file, it seems to make sense.

**Comment by etvedte** [comment]
> We've historically used 400 based on testing by Eerik and Michael. I have bumped it to 520 though
So a TEMPORARY solution for us might be to run FCS externally

We'll look forward to an update on these.

> This is generated for Parus Major using the same input file. But then again, I don't know if you have your own internal meanings for these or what hasher your using.
FCS-GX <-- IN SINGULARITY
{"sum_len":36012401, "num_seqs":3, "num_Ns":500, "len_N50":35873162, "hash":"bab3e7fd1daef57a"
FCS-GX <-- NO CONTAINER
{"sum_len":884723958, "num_seqs":1722, "num_Ns":99800, "len_N50":21627514, "hash":"3718265b5e18f6a0"}

The hash is generated for the input genome as a way for us to potentially validate submissions that attach a clean GX report without needing to run it again internally, but for now we are still screening everything at submission anyway. But yes the stats for the singularity version look incorrect if these are indeed from the same input file.

I appreciate your willingness to try different things out and report back. I am out next week but the team should be monitoring this thread while I'm out in case there is relevant feedback from our end.

**Comment by DLBPointon** [comment]
Thanks @etvedte.

Having a closer look at another failing ticket:

FCS stats
```
{"sum_len":501350308, "num_seqs":7, "num_Ns":70700, "len_N50":86215880, "hash":"d84eb6c3a431faf0"}
```

GFASTATS
```
+++Assembly summary+++:
# scaffolds: 7604
Total scaffold length: 2712073994
Average scaffold length: 356664.12
Scaffold N50: 39296887
Scaffold auN: 36229426.49
Scaffold L50: 22
Largest scaffold: 89855496
Smallest scaffold: 1000
# contigs: 10679
Total contig length: 2711766494
Average contig length: 253934.50
Contig N50: 707488
Contig auN: 919616.93
Contig L50: 1113
Largest contig: 6674267
Smallest contig: 1000
# gaps in scaffolds: 3075
Total gap length in scaffolds: 307500
Average gap length in scaffolds: 100.00
Gap N50 in scaffolds: 100
Gap auN in scaffolds: 100.00
Gap L50 in scaffolds: 1538
Largest gap in scaffolds: 100
Smallest gap in scaffolds: 100
Base composition (A:C:G:T): 834209966:520659403:521056310:835840815
GC content %: 38.41
# soft-masked bases: 0
# segments: 10679
Total segment length: 2711766494
Average segment length: 253934.50
# gaps: 3075
# paths: 7604
```

Talking with @muffato, is it possible that there is a race condition that is consuming the input before stats can complete or something similar with the other processes which consume the input.

**Comment by murphyte** [comment]
As @etvedte mentioned, these errors are reminiscent of some issues reported on https://github.com/ncbi/fcs/issues/80 and  https://github.com/ncbi/fcs/issues/101.  Copying some previous text related to the issue:

> Those symptoms indicate low-level file-system errors in different parts of the internal GX pipeline by different programs/processes. The common factor is that the pertinent file (input FASTA) was being accessed (read) by multiple processes simultaneously, which ordinarily should not be problematic. We were unable to reproduce the issue locally.
> 
> Based on this, we hypothesize that the underlying issue is the same as described here: https://pawsey.atlassian.net/wiki/spaces/US/pages/51929082/Known+Issues+on+Setonix#KnownIssuesonSetonix-ParallelIOwithinContainers
> 
> The putative fix is to add the following workaround: The environment variable `GX_INSTANTIATE_FASTA=1` will initially dump the input FASTA to a temporary file `$OUTPUT_PATH_BASENAME.tmp.fa`. The repeats-stats collection step will access the FASTA from that temporary file, while the `gx align` step will read from the original FASTA, thus avoiding simultaneous access of the same input file.
> 

For your tests using `GX_INSTANTIATE_FASTA=1`, is there a chance it's generating a tmp file of the same name with your parallel executions? That should only be relevant if there's overlapping execution.

I believe there was some possibility of the Setonix issue with multiple processes accessing the same file also affecting access of the GX-db files themselves (in memory), but I don't know why that would only surface when running inside your Nextflow pipeline. We've run up to 32 parallel executions on the same server all with a single shared copy of the database in memory without problems (for prokaryotes; we more typically run 4 parallel jobs with eukaryote genomes). So it seems like there's something about your Nextflow pipeline that's creating an opportunity for file conflicts.

Is your Nextflow pipeline public?

**Comment by DLBPointon** [comment]
Hi @murphyte 

That makes sense. The input files to each instance of the process are different, always `${meta.id}_${assembly_type}_copied_input.fasta` == `iyTipFemo1_PRIMARY_copied_input.fasta` so there isn't a chance of name conflict. I ended up removing the `GX_INSTANTIATE_FASTA=1` and replacing with a hard copy to see if that would help. Neither have very much.

Interestingly, I've also managed to replicate the issue outside of the pipeline in singularity containers. So it could be how our farm uses singularity, especially as this is across multiple versions of the singularity image. Also a recent update to our cluster has upped the success ratio, but whether that is the underlying issue entirely remains unknown. 

I've also run a couple of tests using just the binary, with no issues whatsoever.

The pipeline is public under: https://github.com/sanger-tol/ascc/tree/pre-template-updates (todays work)

Just be aware, it is very much in active development and to a degree needs a re-write. However, i'm trying to get it stable for production in its current form. None of that should be affecting how it runs.

**Comment by murphyte** [comment]
> I've also run a couple of tests using just the binary, with no issues whatsoever.

just running `gx` directly, or via `run_gx.py` or `fcs.py`?

> Also a recent update to our cluster has upped the success ratio, but whether that is the underlying issue entirely remains unknown.

it could be they're trying to address that Setonix issue, but the page for the link I provided above hasn't been updated in a year so it's hard to say. It should be possible to pull everything out of the container and run via `run_gx.py` (that's how we use it internally). If this is related to the Setonix issue and dependent on containers, that might be a workaround.

**Comment by muffato** [comment]
> For your tests using `GX_INSTANTIATE_FASTA=1`, is there a chance it's generating a tmp file of the same name with your parallel executions? That should only be relevant if there's overlapping execution.

Ah ! The HPC team here faced that problem before !

> I've noticed an interesting bug in relation to running Nextflow jobs with singularity on the farm caused by how singularity handles PIDs because of how certain processes use /tmp. What happens is that because by default each nextflow-singularity container gets it's own PID namespace starting from 1 but shares /tmp two copies of the same container can end up fighting over the same files in /tmp. We've noticed this in srst2 and Java's perfdata . We have a workaround
> ```
> export NXF_SINGULARITY_NEW_PID_NAMESPACE=false
> ```
> This disables pid namespacing in nextflow singularity images.

Full bug report at https://github.com/nextflow-io/nextflow/issues/5310

@murphyte : Could that be the reason ?
@DLBPointon : Wanna run some tests with that option ?

**Comment by DLBPointon** [comment]
I'll give it a go, there's a ticket that just will not go through with the current setup that this will be a good test case.

**Comment by DLBPointon** [comment]
Sorry @murphyte  i didn't mean to ignore you, i've been running the binary via `dist/run_gx`


Well `export NXF_SINGULARITY_NEW_PID_NAMESPACE=false` seems to have been a magic bullet in this case.
@LaurenHuet this may help you too.

All 30+ jobs that have been running, including 2 problematic ones (with double digit failures in fcs alone), have all passed through fcs without a single error (bar 1 which complained of a missing database, but we can fix that). These ran along side a couple of samples without the env (accidently to be honest) but those crashed as usual.

It seems like this could be it.

**Comment by murphyte** [comment]
Fantastic! We'll discuss this internally to see if there's something we should add to our documentation, or change our code to avoid problems that might arise from clashing PIDs in /tmp. I'm puzzled over why `export NXF_SINGULARITY_NEW_PID_NAMESPACE=false` isn't the default and only behavior, but it's great that you now have this working.

**Comment by LaurenHuet** [comment]
I'm also running on setonix, so i will add this `export NXF_SINGULARITY_NEW_PID_NAMESPACE=false` for my next run!
Repeadlty just re-running my pipeline eventually lead to all of the successfully finishing this morning, thanks for the help on this one.

**Comment by murphyte** [comment]
@DLBPointon - do your successful runs need to use `GX_INSTANTIATE_FASTA=1` or not? Just trying to have a complete picture of what solved your problem.

**Comment by DLBPointon** [comment]
I did try `GX_INSTANTIATE_FASTA=1` then switched to  `cp 'readlink $fasta' input.fasta` to test, neither worked, though I have a dozen moving through at the minute with a further pared down command, I'll let you know how they go. This will likely be tomorrow at this rate, our HPC is rather chocablock

```
   export GX_NUM_CORES=${task.cpus}

    run_gx.py \\
        --fasta ${fasta} \\
        --gx-db ${database} \\
        --tax-id ${meta.taxid} \\
        --generate-logfile true \\
        --out-basename ${prefix} \\
        --out-dir .
```

**Comment by murphyte** [comment]
`GX_INSTANTIATE_FASTA=1` duplicates the file such that the repeat masking logic and the screening logic use two separate files, which isn't replicated by you simply making a local copy first. That duplication shouldn't be needed, but it was a possible workaround for the setonix issue. 

It may be that your issue is entirely solved by `export NXF_SINGULARITY_NEW_PID_NAMESPACE=false`, which would be helpful to know for others embedding FCS-GX into larger pipelines.

**Comment by DLBPointon** [comment]
Ah ok, i misunderstood then.

Well i've turned `GX_INSTANTIATE_FASTA=1` back on and then run a number of jobs without it too. 

Everything crashed last night but It looks like an issue where the DB was deleted on one node, which happened to be the only node accepting jobs so all 72 fcs jobs died rather unceremoniously.

I've set everything going again and report back.

**Comment by murphyte** [comment]
I think the issue that is possibly helped by `GX_INSTANTIATE_FASTA=1` should always occur if it is indeed a factor (and dependent on setonix and use of a container). It would be independent of issues from multiple parallel runs on the same host. It sounds like you probably don't need it, and your issues were all Nextflow related. Hopefully everything is now sorted out and working well for you.

**Comment by DLBPointon** [comment]
24 tickets went through over the weekend equating to 72 FCS runs all FCS-GX runs passed. 

7 tickets needed re-running due to an issue with a downstream process, but for some reason nextflow couldn't remember FCS passed and re-ran fcs at the same time. I decided to run these with out `GX_INSTANTIATE_FASTA=1` and 1 of them failed with the below, even though it passed fine with the ENV set not the first time.

Both times, the `export NXF_SINGULARITY_NEW_PID_NAMESPACE=false` env was set.

```
-----------------------------------------------------------------------------

tax-id    : 1594266
fasta     : ilCydInqu1_HAPLO_filtered.fasta
size      : 1068.6 MiB
split-fa  : True
BLAST-div : moths
gx-div    : anml:insects
w/same-tax: True
bin-dir   : /usr/local/bin
gx-db     : 2023-01-24/all.gxi build-date: 2023-01-24
gx-ver    : Mar 25 2025 15:00:25; git:v0.5.5-9-gfc836c1; sqlite:3.46.1
output    : ./ilCydInqu1_HAPLO.taxonomy.rpt

-----------------------------------------------------------------------------

Collecting masking statistics...
Using GX_NUM_CORES=32
Error: Process failed with retcode -15: ['/usr/local/bin/gx', 'split-fasta'])


     ********************************************************
     *
     *  Note: the command was terminated by a signal SIGTERM
     *
     ********************************************************
Warning: missing header '##[["GX hits",2,1]]'
Fatal error: taxify.cpp:364 in make_run_info_json(...): Assertion failed: agg_cvg <= 1
Error: Process failed with retcode -15: ['nice', '-n19', '/usr/local/bin/gx', 'align', '--gx-db=2023-01-24/all.gxi', '--repeats-basis-fa=/dev/fd/6'])

     ********************************************************
     *
     *  Note: the command was terminated by a signal SIGTERM
     *
     ********************************************************
Error: Process failed with retcode 1: ['/usr/local/bin/gx', 'taxify', '--gx-db=2023-01-24/all.gxi', '--output=./ilCydInqu1_HAPLO.taxonomy.rpt.tmp', '--asserted-div=anml:insects'])

-----------------------------------------------------------------------------

Traceback (most recent call last):
  File "/usr/local/bin/run_gx.py", line 1202, in <module>
    main()
    ~~~~^^
  File "/usr/local/bin/run_gx.py", line 1177, in main
    run_gx_pipeline(args)
    ~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/bin/run_gx.py", line 817, in run_gx_pipeline
    run(p_zcat_fasta, p_get_fasta_stats, p_save_hits, p_main, tmp_instantiated_fasta_path)
    ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/run_gx.py", line 808, in run
    p_main.wait()
    ~~~~~~~~~~~^^
  File "/usr/local/bin/run_gx.py", line 334, in wait
    assert num_errors == 0, "Had errors."
           ^^^^^^^^^^^^^^^
```

**Comment by murphyte** [comment]
Glad to hear it's nearly always working for you!

> 1 of them failed with the below, even though it passed fine with the ENV set not the first time.

It's hard to say if that failure was caused by not using `GX_INSTANTIATE_FASTA=1` or not. The `missing header '##[["GX hits",2,1]]'` means the GX hits weren't properly passed to the next stage. It may be that the Setonix bug with file access is intermittent and using `GX_INSTANTIATE_FASTA=1` will increase reliability, but I think you'd need more than N=7 to say for sure. But using `GX_INSTANTIATE_FASTA=1` adds very little overhead, so it may be easiest to just use it rather than trying to test further.

**Comment by DLBPointon** [comment]
Hi All,

So over the past month we have had a significant amount of ups and down.

Currently (over the past 2 weeks), we are getting a significant % of jobs failing with the same error as my last message (https://github.com/ncbi/fcs-gx/issues/14#issuecomment-3127448767). The efficacy of the Environment in nextflow seems to have disappeared.

Is there the possibility of any other ideas that may help? Currently, looking at having to revise this part of the pipeline to avoid the use of singularity and going baremetal.

**Comment by etvedte** [comment]
We talked about this internally, and unfortunately don't have any further suggestions to troubleshoot the issue at this time.

The singularity container certainly isn't required to run GX as long as you have python 3.8+. So maybe running outside of the container is worth trying.

**Comment by DLBPointon** [comment]
No problem, we're now useing a bare-metal installed copy and have an internal ticket open for support with IT seeing as we know at least one other institute running FCS with singularity. Happy to report back if they figure something out, even if it's something for the docs.
